package com.smart.smartble.event;

/**
 * @author ARZE
 * @version 创建时间：2016/12/13 16:15
 * @说明
 */
public enum Action {

    NONE,

    /**
     * 普通ack返回给mcu
     */

    REQUEST_ACTION_NORMAL_ACK,

    /**
     * 蓝牙连接
     */
    REQUEST_ACTION_AUTHORIZATION, // 授权

    /**
     * 拍照
     */
    REQUEST_ACTION_CAMERA,//进入拍照
    REQUEST_ACTION_HEART_CAMERA,//拍照心跳包
    REQUEST_ACTION_TAKE_PHOTON,

    /**
     * 运动
     */

    REQUEST_ACTION_SET_STEP_TARGET,



    /**
     * 提醒
     */
    REQUEST_ACTION_SET_NOTIFY_SETTING,
    REQUEST_ACTION_SET_NOTIFY,
    REQUEST_ACTION_DISCONNECT_NOTIFY,
    REQUEST_ACTION_GET_DISCONNECT_NOTIFY_SETTING,
    REQUEST_ACTION_FIND_PHONE,
    REQUEST_ACTION_CALL_NOTIFY,
    REQUEST_ACTION_PHONE_EVENT,
    REQUEST_ACTION_CANCEL_NOTIFY,

    /**
     * 闹钟
     */

    REQUEST_ACTION_SET_ALARM,
    REQUEST_ACTION_GET_ALARM,

    /**
     * 校时
     */
    REQUEST_ACTION_TIME,
    REQUEST_ACTION_HEART_TIME,
    REQUEST_ACTION_SET_POSITION_TIME,
    REQUEST_ACTION_SET_MCU_TIME,
    REQUEST_ACTION_TIME_SMALL_POSITION,
    REQUEST_ACTION_SET_SECOND_TIME,
    REQUEST_ACTION_GET_TIME,
    REQUEST_ACTION_ASK_TIME,
    REQUEST_ACTION_GET_SECOND_TIME,

    /**
     * ota
     */
    REQUEST_ACTION_START_OTA,
    REQUEST_ACTION_ASK_MCU_FILE,
    REQUEST_ACTION_ASK_FILE_DATA,
    REQUEST_ACTION_ASK_MCU_FILE_STATUS,
    REQUEST_ACTION_ASK_MCU_DATA_OK,
    REQUEST_ACTION_SET_OTA_END,
    REQUEST_ACTION_BEGIN_UPDATE_MCU,

    /**
     * 数据传输
     */
    REQUEST_ACTION_GET_ONE_DAY,
    REQUEST_ACTION_UPDATE_DATA, //请求数据//根据index获取具体数据
    REQUEST_ACTION_CHANGE_PROTOCOL_TIME,
    REQUEST_ACTION_BLE_CONN_SUCCESSFUL,
    REQUEST_ACTION_REPLAY_DATA,
    REQUEST_ACTION_SET_TARGET,
    REQUEST_ACTION_GET_TARGET,


    REQUEST_ACTION_GET_CONTENT, //获取数据目录
    REQUEST_ACTION_GET_CONTENT_MESSAGE,//获取数据目录信息
    REQUEST_ACTION_GET_DATA_BY_INDEX,
    REQUEST_ACTION_GET_CONTENT_DATA,
    REQUEST_ACTION_DELETE_DATA_BY_STYLE,
    REQUEST_ACTION_DELETE_DATA_BY_UTC,
    /**
     * 手表的属性
     */

    REQUEST_ACTION_GET_ELECTRICITY,
    REQUEST_ACTION_CHANGE_BLE_CAST,
    REQUEST_ACTION_REQUEST_VERSION,
    REQUEST_ACTION_GET_SN,

    /**
     * 蓝牙操作
     */

    REQUEST_ACTION_CHANGE_BLE_INTERVAL,
    REQUEST_ACTION_REPLAY_CHANGE_BLE,



    REQUEST_ACTION_SEND_TARGET,
    REQUEST_ACTION_REQUEST_TARGET,
    REQUEST_ACTION_SEND_CLOCK,
    REQUEST_ACTION_REQUEST_CLOCK,
    REQUEST_ACTION_SEND_ALARM,
    REQUEST_ACTION_REQUEST_ALARM,
    REQUEST_ACTION_SEND_POWER,
    REQUEST_ACTION_REQUEST_POWER,
    REQUEST_ACTION_SEND_INTERVAL,
    REQUEST_ACTION_ALARM_REPLAY,

}
